kind: Deployment
apiVersion: apps/v1
metadata:
  name: obligato-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: obligato-server
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: obligato-server-svc
spec:
  ports:
    - name: http-3001
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: nodejs-app